name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout - clone repository
      uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        git submodule update --init --recursive
        sbt clean android:package-release
    - name: Upload to artifact file
      uses: actions/upload-artifact@v1
      with:
        name: simple-obfs-android
        path: target/android/output/
        
